name: Action that runs on release

# Should only run on release
on:
  release

jobs:  
  build:
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v2
      - name: Print env variables
        run: printenv
